import os
import json
import pandas as pd
import mne
import numpy as np
from pathlib import Path
from typing import Dict, List, Optional, Callable, Any
from datetime import datetime
import shutil
from natsort import natsorted
import glob
import re
import multiprocessing
from functools import partial
        
from multiprocessing import Pool
from pathlib import Path
from datetime import datetime
from typing import List, Callable, Dict, Any, Tuple
import numpy as np
from tqdm import tqdm  # 用于进度条，可选

class BIDSProcessor:
    """BIDS处理器"""
    
    def __init__(self,  
                 bids_root: str, 
                 dataset_name: str = "EEG_Dataset",
                 task: str = "sleep",
                 session: str = "ses-1",
                 start_subject_id: int = 1):
        """
        初始化BIDS处理器
        
        Args:
            bids_root: BIDS根目录
            dataset_name: 数据集名称
            task: 任务名称
            session: session名称
            start_subject_id: 起始subject_id编号
        """
        self.bids_root = Path(bids_root)
        self.dataset_name = dataset_name
        self.task = task
        self.session = session
        
        # 计数器 - 从指定起始值开始
        self.start_subject_id = start_subject_id
        self.subject_counter = start_subject_id
        
        # 总记录时长累计（小时）- 初始化为0，后续会从dataset_description.json读取
        self.total_recording_hours = 0.0
        
        # 创建BIDS基础结构
        self._create_bids_structure()
        
        # 初始化时从dataset_description.json读取现有数据集的total_recording_hours
        self._init_total_recording_hours()
        
        print(f"BIDS处理器初始化完成")
        print(f"BIDS目录: {bids_root}")
        print(f"数据集: {dataset_name}")
        print(f"任务: {task}")
        print(f"起始subject_id: {self._format_subject_id(start_subject_id)}")
        print(f"当前数据集已累计记录时长: {self.total_recording_hours:.2f} 小时")
    
    def _init_total_recording_hours(self):
        """从dataset_description.json初始化当前数据集的total_recording_hours"""
        desc_path = self.bids_root / "dataset_description00.json"
        
        if desc_path.exists():
            with open(desc_path, 'r', encoding='utf-8') as f:
                dataset_desc = json.load(f)
            
            # 查找当前数据集
            for info in dataset_desc.get("DatasetInfo", []):
                if info.get("name") == self.dataset_name:
                    self.total_recording_hours = info.get("total_recording_hours", 0.0)
                    break
    
    def _format_subject_id(self, subject_num: int) -> str:
        """格式化subject_id为7位数"""
        return f"{subject_num:07d}"
    
    def _create_bids_structure(self):
        """创建BIDS基础目录结构"""
        # 创建必需目录
        (self.bids_root / "derivatives").mkdir(parents=True, exist_ok=True)
        (self.bids_root / "sourcedata").mkdir(parents=True, exist_ok=True)
        
        # 读取或创建dataset_description.json
        self._create_or_update_dataset_description()
        
        # 创建空的participants.tsv
        participants_df = pd.DataFrame(columns=[
            'participant_id', 'age', 'sex', 'handedness', 'group'
        ])
        participants_df.to_csv(self.bids_root / "participants.tsv", 
                              sep='\t', index=False, na_rep='n/a')
    
    def _create_or_update_dataset_description(self):
        """创建或更新dataset_description.json"""
        desc_path = self.bids_root / "dataset_description00.json"
        
        if desc_path.exists():
            # 读取现有的dataset_description.json
            with open(desc_path, 'r', encoding='utf-8') as f:
                dataset_desc = json.load(f)
        else:
            # 创建新的dataset_description.json
            dataset_desc = {
                "Name": f"SLEEP_EEG_Data",
                "BIDSVersion": "1.8.0",
                "License": "CC0",
                "Authors": ["AutoGenerated"],
                "GeneratedBy": [
                    {
                        "Name": "BIDSProcessor",
                        "Version": "1.0",
                        "Description": "BIDS data processing pipeline"
                    }
                ],
                "DatasetInfo": [],  # 用于记录多个数据集信息
                "DateGenerated": datetime.now().isoformat(),
                "LastUpdated": datetime.now().isoformat(),
                "TotalSubjects": 0,  # 总被试数量
                "TotalRecordingHours": 0.0  # 新增：总记录时长（小时）
            }
        
        # 保存到类变量中，供后续使用
        self.dataset_desc = dataset_desc
        
        # 写入文件
        with open(desc_path, 'w', encoding='utf-8') as f:
            json.dump(dataset_desc, f, indent=4, ensure_ascii=False)
    
    def _add_dataset_info_before_processing(self, file_count: int, planned_subject_range: tuple):
        """
        在处理开始前添加数据集信息到dataset_description.json
        
        Args:
            file_count: 计划处理的文件数量
            planned_subject_range: 计划使用的subject_id范围 (start, end)
        """
        start_id, end_id = planned_subject_range
        
        # 检查是否已存在相同名称的数据集
        existing_total_recording_hours = self.total_recording_hours  # 默认为当前累计值
        
        # 重新读取dataset_description.json以确保获取最新值
        desc_path = self.bids_root / "dataset_description00.json"
        if desc_path.exists():
            with open(desc_path, 'r', encoding='utf-8') as f:
                dataset_desc = json.load(f)
            
            for info in dataset_desc.get("DatasetInfo", []):
                if info.get("name") == self.dataset_name:
                    # 使用现有的total_recording_hours，而不是重置为0
                    existing_total_recording_hours = info.get("total_recording_hours", self.total_recording_hours)
                    break
        
        dataset_info = {
            "name": self.dataset_name,
            "file_count": file_count,
            "planned_start_subject_id": self._format_subject_id(start_id),
            "planned_end_subject_id": self._format_subject_id(end_id),
            "creation_time": datetime.now().isoformat(),
            "task": self.task,
            "session": self.session,
            "total_recording_hours": existing_total_recording_hours  # 保留已有的记录时长
        }
        
        # 添加到DatasetInfo列表
        if "DatasetInfo" not in self.dataset_desc:
            self.dataset_desc["DatasetInfo"] = []
        
        # 检查是否已存在相同名称的数据集
        found_existing = False
        for i, info in enumerate(self.dataset_desc["DatasetInfo"]):
            if info.get("name") == self.dataset_name:
                # 更新现有记录，但保留total_recording_hours
                existing_hours = info.get("total_recording_hours", existing_total_recording_hours)
                dataset_info["total_recording_hours"] = existing_hours
                self.dataset_desc["DatasetInfo"][i] = dataset_info
                found_existing = True
                break
        
        if not found_existing:
            # 添加新记录
            self.dataset_desc["DatasetInfo"].append(dataset_info)
        
        # 更新dataset_description.json
        self._update_dataset_description_file()
        
        print(f"  数据集 '{self.dataset_name}' 初始化: 计划处理 {file_count} 个文件")
        print(f"  当前累计记录时长: {dataset_info['total_recording_hours']:.2f} 小时")
    
    def _update_dataset_description_file(self):
        """更新dataset_description.json文件"""
        # 更新汇总统计（如果DatasetInfo存在）
        if "DatasetInfo" in self.dataset_desc:
            self.dataset_desc["TotalSubjects"] = sum(
                info.get("file_count", 0) for info in self.dataset_desc["DatasetInfo"]
            )
            
            # 更新总记录时长（累计所有数据集）
            self.dataset_desc["TotalRecordingHours"] = sum(
                info.get("total_recording_hours", 0.0) for info in self.dataset_desc["DatasetInfo"]
            )
        
        self.dataset_desc["LastUpdated"] = datetime.now().isoformat()
        
        # 写入文件
        desc_path = self.bids_root / "dataset_description00.json"
        with open(desc_path, 'w', encoding='utf-8') as f:
            json.dump(self.dataset_desc, f, indent=4, ensure_ascii=False)
    
    def _update_dataset_recording_hours(self, recording_hours: float):
        """
        更新数据集的总记录时长
        
        Args:
            recording_hours: 新增的记录时长（小时）
        """
        # 累加总记录时长
        self.total_recording_hours += recording_hours
        
        # 更新dataset_description.json
        desc_path = self.bids_root / "dataset_description00.json"
        
        if not desc_path.exists():
            return
        
        with open(desc_path, 'r', encoding='utf-8') as f:
            dataset_desc = json.load(f)
        
        # 查找当前数据集
        dataset_found = False
        for i, info in enumerate(dataset_desc.get("DatasetInfo", [])):
            if info.get("name") == self.dataset_name:
                # 获取当前的记录时长并累加
                current_hours = info.get("total_recording_hours", 0.0)
                dataset_desc["DatasetInfo"][i]["total_recording_hours"] = current_hours + recording_hours
                dataset_found = True
                break
        
        # 如果数据集不存在，创建新记录
        if not dataset_found:
            dataset_info = {
                "name": self.dataset_name,
                "file_count": 0,  # 稍后会在_batch_process_files中更新
                "planned_start_subject_id": self._format_subject_id(self.start_subject_id),
                "planned_end_subject_id": self._format_subject_id(self.start_subject_id),
                "creation_time": datetime.now().isoformat(),
                "task": self.task,
                "session": self.session,
                "total_recording_hours": recording_hours
            }
            if "DatasetInfo" not in dataset_desc:
                dataset_desc["DatasetInfo"] = []
            dataset_desc["DatasetInfo"].append(dataset_info)
        
        # 更新汇总统计
        dataset_desc["TotalSubjects"] = sum(
            info.get("file_count", 0) for info in dataset_desc.get("DatasetInfo", [])
        )
        
        # 更新总记录时长（累计所有数据集）
        dataset_desc["TotalRecordingHours"] = sum(
            info.get("total_recording_hours", 0.0) for info in dataset_desc.get("DatasetInfo", [])
        )
        
        dataset_desc["LastUpdated"] = datetime.now().isoformat()
        
        # 保存更新
        with open(desc_path, 'w', encoding='utf-8') as f:
            json.dump(dataset_desc, f, indent=4, ensure_ascii=False)
        
        # 更新类变量
        self.dataset_desc = dataset_desc
        
        # 获取更新后的当前数据集总记录时长
        current_total = 0.0
        for info in dataset_desc.get("DatasetInfo", []):
            if info.get("name") == self.dataset_name:
                current_total = info.get("total_recording_hours", 0.0)
                break
        
        print(f"  已更新dataset_description.json: 新增 {recording_hours:.2f} 小时")
        print(f"  当前数据集总记录时长: {current_total:.2f} 小时")
        print(f"  所有数据集总记录时长: {dataset_desc['TotalRecordingHours']:.2f} 小时")
    
    def get_next_subject_id(self) -> str:
        """获取下一个subject_id，格式化为7位数"""
        subject_id = self._format_subject_id(self.subject_counter)
        self.subject_counter += 1
        return subject_id
    
    

    def h5_to_edf(self, h5_filepath, edf_filepath):
        """
        使用MNE库将H5文件转换为EDF/BDF文件，修复采样率问题
        """
        import h5py
        import mne
        import numpy as np
        from datetime import datetime
        import os
        
        with h5py.File(h5_filepath, 'r') as h5f:
            fs = int(h5f['signals/eeg'].attrs['fs'])
            
            # 收集所有通道数据
            signals = []
            channel_names = []
            channel_types = []
            
            # 提取EEG通道
            eeg_group = h5f['signals/eeg']
            for ch_name in eeg_group.keys():
                data = eeg_group[ch_name][:]
                signals.append(data)
                channel_names.append(ch_name)
                channel_types.append('eeg')
            
            # 提取EMG通道
            emg_group = h5f['signals/emg']
            for ch_name in emg_group.keys():
                data = emg_group[ch_name][:]
                signals.append(data)
                channel_names.append(ch_name)
                channel_types.append('emg')
            
            # 提取EOG通道
            eog_group = h5f['signals/eog']
            for ch_name in eog_group.keys():
                data = eog_group[ch_name][:]
                signals.append(data)
                channel_names.append(ch_name)
                channel_types.append('eog')
            
            # 检查所有信号长度是否一致
            signal_lengths = [len(signal) for signal in signals]
            if len(set(signal_lengths)) > 1:
                print(f"警告: 信号长度不一致: {signal_lengths}")
                # 使用最小长度
                min_length = min(signal_lengths)
                signals = [signal[:min_length] for signal in signals]
                print(f"统一长度为: {min_length}")
            
            # 转换为numpy数组，形状为 (n_channels, n_samples)
            data_array = np.array(signals, dtype=np.float32)
            n_channels, n_samples = data_array.shape
            
            print(f"数据形状: {data_array.shape}")
            print(f"原始采样率: {fs} Hz")
            print(f"持续时间: {n_samples/fs/60:.2f} 分钟")
            
            import pyedflib
            
            # **关键修复：使用EDF格式而不是BDF格式**
            # BDF格式对采样率有限制，EDF格式更灵活
            with pyedflib.EdfWriter(
                edf_filepath,
                n_channels=n_channels,
                file_type=pyedflib.FILETYPE_EDFPLUS  # 改为EDFPLUS格式
            ) as f:
                
                # # 设置患者信息
                f.setPatientCode("000")
                f.setPatientName("H5_Converted")
                
                # 设置设备信息
                f.setEquipment("H5_to_EDF_Converter")
                
                # 设置开始时间
                f.setStartdatetime(datetime.now())
                
                # 设置通道信息 - 使用正确的参数名
                for i in range(n_channels):
                    signal_data = data_array[i]
                    
                    # 计算物理范围
                    phys_max = max(100.0, float(signal_data.max()))
                    phys_min = min(-100.0, float(signal_data.min()))
                    
                    # 确保范围合理
                    if abs(phys_max - phys_min) < 1.0:
                        phys_max = 100.0
                        phys_min = -100.0
                    
                    # **关键修复：使用正确的参数名**
                    ch_info = {
                        'label': channel_names[i],
                        'dimension': 'uV',  # EDF通常使用uV而不是mV
                        'sample_frequency': fs,  # 正确的参数名是'sample_rate'
                        'physical_max': phys_max,
                        'physical_min': phys_min,
                        'digital_max': 32767,
                        'digital_min': -32768,
                        'transducer': channel_types[i].upper(),
                        'prefilter': ''
                    }
                    f.setSignalHeader(i, ch_info)
                
                # 写入数据
                f.writeSamples(data_array)
                
                print(f"✓ 使用EDF格式创建: {edf_filepath}")
        
        # 验证文件
        if os.path.exists(edf_filepath):
            file_size = os.path.getsize(edf_filepath)
            print(f"文件大小: {file_size/1024/1024:.2f} MB")
            print(f"通道数: {len(channel_names)}")
            print(f"采样率: {fs} Hz")
            print(f"信号长度: {n_samples/fs/3600:.2f} 小时")
            return edf_filepath
        else:
            raise ValueError(f"无法创建文件: {edf_filepath}")
    
    def copy_source_to_bids(self, 
                           source_file: str, 
                           subject_id: Optional[str] = None,
                           overwrite: bool = False) -> Dict:
        """
        复制源文件到BIDS原始数据目录
        
        Args:
            source_file: 源文件路径
            subject_id: 可选的自定义subject_id
            overwrite: 是否覆盖已存在的文件
            
        Returns:
            复制结果字典
        """
        source_path = Path(source_file)
        
        if not source_path.exists():
            raise FileNotFoundError(f"源文件不存在: {source_file}")
        
        # 生成或使用提供的subject_id
        if subject_id is None:
            subject_id = self.get_next_subject_id()
        else:
            # 确保subject_id是字符串格式
            subject_id = str(subject_id)
        
        # 检查文件扩展名
        ext = source_path.suffix.lower()
        if ext not in ['.bdf', '.edf', '.fif']:
            print(f"警告: 不支持的文件格式 {ext}，跳过文件 {source_path.name}")
            return {"status": "skipped", "reason": f"Unsupported format {ext}"}
        
        # 创建被试目录
        subject_dir = self.bids_root /"sourcedata"/ f"sub-{subject_id}" / self.session / "eeg"
        subject_dir.mkdir(parents=True, exist_ok=True)
        
        # 生成BIDS文件名
        bids_filename = f"sub-{subject_id}_{self.session}_task-{self.task}_eeg{ext}"
        bids_path = subject_dir / bids_filename
        
        # 检查文件是否已存在
        if bids_path.exists() and not overwrite:
            print(f"文件已存在: {bids_path.name}")
            return {"status": "skipped", "reason": f"file already exists: {bids_path.name}"}
        

        # 复制文件
        shutil.copy2(source_path, bids_path)
        print(f"复制源文件: {source_path.name} -> {bids_path.name}")
        
        # 尝试读取文件以获取元数据
        recording_duration = 0.0
        recording_hours = 0.0
        if ext == '.edf':
            try:
                raw = mne.io.read_raw_edf(source_path, preload=False, verbose=False)
                recording_duration = raw.times[-1]  # 获取记录时长（秒）
                recording_hours = recording_duration / 3600.0  # 转换为小时
            except Exception as e:
                print(f"  警告: 无法读取EDF文件元数据: {e}")
                raw = None
        elif ext == '.bdf':
            try:
                raw = mne.io.read_raw_bdf(source_path, preload=False, verbose=False)
                recording_duration = raw.times[-1]  # 获取记录时长（秒）
                recording_hours = recording_duration / 3600.0  # 转换为小时
            except Exception as e:
                print(f"  警告: 无法读取BDF文件元数据: {e}")
                raw = None

        elif ext == '.fif':
            try:
                raw = mne.io.read_raw_fif(source_path, preload=False, verbose=False)
                recording_duration = raw.times[-1]  # 获取记录时长（秒）
                recording_hours = recording_duration / 3600.0  # 转换为小时
            except Exception as e:
                print(f"  警告: 无法读取FIF文件元数据: {e}")
    
        if raw is not None:
            # 创建JSON侧文件
            self._create_source_json_sidecar(raw, bids_path)
            
            # 创建channels.tsv
            self._create_channels_tsv(raw, bids_path)
            
            # # 在复制源文件后立即更新dataset_description.json中的记录时长
            # if recording_hours > 0:
            #     self._update_dataset_recording_hours(recording_hours)
        else:
            print(f"  警告: 无法创建JSON和channels.tsv文件，因为无法读取文件元数据")
        
        # 更新participants.tsv
        self._update_participants_tsv(subject_id)
        
        return {
            "status": "success",
            "subject_id": subject_id,
            "session": self.session,
            "task": self.task,
            "source_file": str(source_path),
            "bids_file": str(bids_path),
            "file_type": ext,
            "recording_duration": recording_duration,  # 记录时长（秒）
            "recording_hours": recording_hours         # 记录时长（小时）
        }
    
    def _create_source_json_sidecar(self, raw, bids_path: Path):
        """为源文件创建JSON侧文件"""
        json_path = bids_path.with_suffix('.json')
        
        # 计算通道数量
        eeg_chs = mne.pick_types(raw.info, eeg=True)
        eog_chs = mne.pick_types(raw.info, eog=True)
        ecg_chs = mne.pick_types(raw.info, ecg=True)
        emg_chs = mne.pick_types(raw.info, emg=True)
        
        sidecar = {
            "TaskName": self.task,
            "SamplingFrequency": float(raw.info['sfreq']),
            "PowerLineFrequency": 50.0,
            "SoftwareFilters": "n/a",
            "EEGChannelCount": len(eeg_chs),
            "EOGChannelCount": len(eog_chs),
            "ECGChannelCount": len(ecg_chs),
            "EMGChannelCount": len(emg_chs),
            "MiscChannelCount": len(raw.info['chs']) - (len(eeg_chs) + len(eog_chs) + len(ecg_chs) + len(emg_chs)),
            "TriggerChannelCount": len(mne.pick_types(raw.info, stim=True)),
            "RecordingDuration": float(raw.times[-1]),
            "RecordingType": "continuous",
        }
        
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(sidecar, f, indent=4, ensure_ascii=False)
    
    def _create_channels_tsv(self, raw, bids_path: Path):
        """创建channels.tsv文件"""
        channels_path = bids_path.with_suffix('.tsv').with_name(
            bids_path.stem + '_channels.tsv'
        )
        
        channels_data = []
        for ch in raw.info['chs']:
            channel_type = self._map_channel_type(ch)
            
            channel_info = {
                'name': ch['ch_name'],
                'type': channel_type,
                'units': 'microV' if channel_type in ['EEG', 'EOG', 'ECG', 'EMG'] else 'n/a',
                'description': f"{channel_type} channel",
                'status': 'good'
            }
            
            channels_data.append(channel_info)
        
        channels_df = pd.DataFrame(channels_data)
        channels_df.to_csv(channels_path, sep='\t', index=False, na_rep='n/a', encoding='utf-8')
    
    def _map_channel_type(self, ch_info) -> str:
        """映射通道类型"""
        ch_name = ch_info['ch_name'].upper()
        ch_kind = ch_info['kind']
        
        # MNE类型映射
        if ch_kind == 2:  # EEG
            return 'EEG'
        elif ch_kind == 202:  # EOG
            return 'EOG'
        elif ch_kind == 402:  # ECG
            return 'ECG'
        elif ch_kind == 302:  # EMG
            return 'EMG'
        elif ch_kind == 3:  # Stimulus
            return 'TRIG'  
        
        return 'MISC'
    
    def _update_participants_tsv(self, subject_id: str, demographics: Dict = None):
        """更新participants.tsv文件"""
        participants_path = self.bids_root / "participants.tsv"
        
        # 读取现有的participants.tsv
        if participants_path.exists() and participants_path.stat().st_size > 0:
            participants_df = pd.read_csv(participants_path, sep='\t')
        else:
            participants_df = pd.DataFrame(columns=['participant_id'])
        
        # 检查被试是否已存在
        subject_clean = subject_id.replace('sub-', '') if 'sub-' in subject_id else subject_id
        
        if subject_clean not in participants_df['participant_id'].values:
            # 创建新被试行
            new_participant = {
                'participant_id': subject_clean,
                'age': demographics.get('age', 'n/a') if demographics else 'n/a',
                'sex': demographics.get('sex', 'n/a') if demographics else 'n/a',
                'handedness': demographics.get('handedness', 'n/a') if demographics else 'n/a',
                'group': demographics.get('group', 'n/a') if demographics else 'n/a'
            }
            
            # 添加到DataFrame
            new_row = pd.DataFrame([new_participant])
            participants_df = pd.concat([participants_df, new_row], ignore_index=True)
            participants_df.to_csv(participants_path, sep='\t', index=False, na_rep='n/a', encoding='utf-8')
    
    def save_processed_to_derivatives(self, 
                                     process_func, 
                                     file_path,
                                     subject_id: str,
                                     description: str = "clean",
                                     pipeline_name: str = "preprocessed",
                                     overwrite: bool = False) -> Dict:
        """
        保存处理后的数据到derivatives目录
        
        Args:
            raw: 处理后的EEG数据
            subject_id: subject ID
            description: 数据描述
            pipeline_name: 处理流水线名称
            overwrite: 是否覆盖已存在文件
            
        Returns:
            保存结果字典
        """
        # 创建derivatives目录
        deriv_root = self.bids_root / "derivatives" / pipeline_name
        deriv_root.mkdir(parents=True, exist_ok=True)
        
        # 创建被试目录
        subject_dir = deriv_root / f"sub-{subject_id}" / self.session / "eeg"
        subject_dir.mkdir(parents=True, exist_ok=True)
        
        # 生成BIDS文件名
        bids_filename = f"sub-{subject_id}_{self.session}_task-{self.task}_desc-{description}_eeg.bdf"
        bids_path = subject_dir / bids_filename
        

        # 检查文件是否已存在（edf或bdf格式）
        file_base = f"sub-{subject_id}_{self.session}_task-{self.task}_desc-{description}_eeg"
        bdf_exists = (subject_dir / f"{file_base}.bdf").exists()
        edf_exists = (subject_dir / f"{file_base}.edf").exists()
        fif_exists = (subject_dir / f"{file_base}.fif").exists()

        # # 检查文件是否已存在
        if bdf_exists or edf_exists or fif_exists:
            print(f"处理后的文件已存在，跳过: {bids_path.name}")
            return {
                "status": "skipped",
                "subject_id": subject_id,
                "session": self.session,
                "task": self.task,
                "file_path": str(bids_path)
            }

        # 处理并保存BDF文件
        # target_file_path = None
        # temp_path = r"/mnt/nas1/Neuromodulation/human/temp"
        # target_file_path = os.path.join(temp_path, f"{subject_id}.edf")
        # if file_path.endswith('.h5'):
        #     # target_file_path = file_path.replace('.h5', '.bdf')
        #     if not os.path.exists(target_file_path):
        #         file_path = self.h5_to_edf(file_path, target_file_path)
        #     else:
        #         file_path = target_file_path

        # if file_path.endswith('.fif'):
        #     if not os.path.exists(target_file_path):
        #         file_path = self.edf_to_bdf(file_path, target_file_path)
        #     else:
        #         file_path = target_file_path

        if process_func is not None:
            print(f"faster处理: {file_path}")
            raw = process_func(file_path)
        else:#如果没有提供处理函数，使用默认的简单处理
            raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
            raw.filter(0.5, 40., fir_design='firwin', verbose=False)
            raw.notch_filter(50., verbose=False)
        try:
            mne.export.export_raw(bids_path, raw, fmt="bdf", overwrite=True)
            print(f"保存处理后的bdf数据: {bids_path.name}")
        except Exception as e:
            print(f"保存处理后的数据失败,保存为fif文件: {e}")
            bids_filename = f"sub-{subject_id}_{self.session}_task-{self.task}_desc-{description}_eeg.fif"
            bids_path = subject_dir / bids_filename
            raw.save(bids_path, overwrite=True)
            
        # 创建处理信息JSON文件
        self._create_processed_json_sidecar(raw, bids_path, description, pipeline_name)
        
        # 创建channels.tsv
        self._create_channels_tsv(raw, bids_path)
        
        # 创建处理日志
        self._create_processing_log(bids_path, pipeline_name, description)
        
        return {
            "status": "success",
            "subject_id": subject_id,
            "session": self.session,
            "task": self.task,
            "file_path": str(bids_path),
            "pipeline": pipeline_name,
            "description": description
        }
    
    def _create_processed_json_sidecar(self, raw, bids_path: Path, 
                                     description: str, pipeline_name: str):
        """为处理后的数据创建JSON侧文件"""
        json_path = bids_path.with_suffix('.json')
        
        # 计算通道数量
        eeg_chs = mne.pick_types(raw.info, eeg=True)
        eog_chs = mne.pick_types(raw.info, eog=True)
        ecg_chs = mne.pick_types(raw.info, ecg=True)
        emg_chs = mne.pick_types(raw.info, emg=True)
        
        sidecar = {
            "TaskName": self.task,
            "SamplingFrequency": float(raw.info['sfreq']),
            "PowerLineFrequency": 50.0,
            "SoftwareFilters": "n/a",
            "EEGChannelCount": len(eeg_chs),
            "EOGChannelCount": len(eog_chs),
            "ECGChannelCount": len(ecg_chs),
            "EMGChannelCount": len(emg_chs),
            "MiscChannelCount": len(raw.info['chs']) - (len(eeg_chs) + len(eog_chs) + len(ecg_chs) + len(emg_chs)),
            "TriggerChannelCount": len(mne.pick_types(raw.info, stim=True)),
            "RecordingDuration": float(raw.times[-1]),
            "RecordingType": "continuous",
            "Description": f"Processed EEG data - {description}",
            "PipelineName": pipeline_name,
            "ProcessingDate": datetime.now().isoformat(),
            "ProcessingSteps": [
                "Bandpass filtering: 0.5-40 Hz",
                "Notch filtering: 50 Hz",
                "Re-referencing",
                "ECG artifact removal and detrending",
                "FASTER bad channel and bad epoch detection"
            ]
        }
        
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(sidecar, f, indent=4, ensure_ascii=False)
    
    def _create_processing_log(self, bids_path: Path, pipeline_name: str, description: str):
        """创建处理日志文件"""
        log_path = bids_path.with_suffix('.log').with_name(
            bids_path.stem + '_processing.log'
        )
        
        log_content = f"""# Processing Log
                    File: {bids_path.name}
                    Pipeline: {pipeline_name}
                    Description: {description}
                    Date: {datetime.now().isoformat()}

                    ## Processing Steps
                    1. Bandpass filtering: 0.5-40 Hz
                    2. Notch filtering: 50 Hz
                    3. Re-referencing
                    4. ECG artifact removal and detrending
                    5. FASTER bad channel and bad epoch detection

                    ## Software Information
                    - MNE-Python version: {mne.__version__}
                    - Processing script: BIDSProcessor
                    - Processing date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

                    ## Notes
                    This file was automatically generated by BIDSProcessor.
                    """
                            
        with open(log_path, 'w', encoding='utf-8') as f:
            f.write(log_content)


    def batch_process_files(self, 
                            file_paths: List[str], 
                            task: str = "sleep",
                            process_func: Callable = None,
                            pipeline_name: str = "preprocessed",
                            description: str = "clean",
                            num_processes: int = None,
                            **kwargs) -> Dict[str, Any]:
        """ 
        Args:
            file_paths: 文件路径列表
            task: 任务名称
            process_func: 处理函数，接收文件路径返回处理后的raw
            pipeline_name: 处理流水线名称
            description: 数据描述
            num_processes: 进程数，默认使用CPU核心数
            chunksize: 每个工作进程一次处理的任务数，可以提高大数据集的处理效率
            **kwargs: 传递给process_func的参数
            
        Returns:
            处理结果字典，包含详细统计信息
        """

        # 设置进程数
        if num_processes is None:
            num_processes = 2 #multiprocessing.cpu_count()//2
        # 根据文件数量自动选择chunksize
        num_files = len(file_paths)
        if num_files < 10:
            chunksize = 1
        elif num_files < 50:
            chunksize = 2
        elif num_files < 100:
            chunksize = 4
        else:
            chunksize = 8

        # 0. 在处理开始前，先添加到dataset_description.json
        planned_end_id = self.start_subject_id + len(file_paths) - 1
        self._add_dataset_info_before_processing(
            file_count=len(file_paths),
            planned_subject_range=(self.start_subject_id, planned_end_id)
        )
        
        results = {
            "total_files": len(file_paths),
            "processed_success": 0,
            "processed_failed": 0,
            "copy_success": 0,
            "copy_failed": 0,
            "details": [],
            "start_subject_id": self._format_subject_id(self.start_subject_id),
            "end_subject_id": None,
            "dataset_name": self.dataset_name,
            "processing_start_time": datetime.now().isoformat(),
            "processing_end_time": None,
            "total_recording_seconds": 0.0,
            "total_recording_hours": 0.0,
            "num_processes": num_processes,
            "chunksize": chunksize
        }
        
        print(f"开始批量处理 {len(file_paths)} 个文件，使用 {num_processes} 个进程")
        print(f"chunksize: {chunksize}")
        print("=" * 60)
        
        # 为每个文件预分配subject_id
        subject_ids = []
        for i in range(len(file_paths)):
            subject_id = self.get_next_subject_id()
            subject_ids.append(subject_id)
        
        # 创建处理任务列表（索引，文件路径，subject_id）
        tasks = list(enumerate(zip(file_paths, subject_ids), 1))
        completed_count = 0
        
        # 多进程处理
        with Pool(processes=num_processes) as pool:
            # 使用偏函数固定参数
            worker_func = partial(
                self._process_single_file_worker,
                task=task,
                process_func=process_func,
                pipeline_name=pipeline_name,
                description=description,
                **kwargs
            )
            
            for result in pool.imap_unordered(worker_func, tasks, chunksize=chunksize):
                completed_count += 1
                
                # 解包结果
                index = result['index']
                file_path = result['file_path']
                subject_id = result['subject_id']
                
                # 统计处理状态
                if result['process_status'] == 'success':
                    results["processed_success"] += 1
                elif result['process_status'] == 'skipped':
                    # 跳过但统计为成功
                    results["processed_success"] += 1
                else:
                    results["processed_failed"] += 1
                
                # 统计复制状态
                if result['copy_status'] == 'success':
                    results["copy_success"] += 1
                else:
                    results["copy_failed"] += 1
                
                # 累加记录时长
                if result["copy_status"] == 'success':
                    recording_seconds = result.get('recording_duration', 0.0)
                    recording_hours = result.get('recording_hours', recording_seconds / 3600.0)
                    results["total_recording_seconds"] += recording_seconds
                    results["total_recording_hours"] += recording_hours
                    # 更新dataset_description.json中的记录时长
                    self._update_dataset_recording_hours(recording_hours)
                
                # 添加到详情
                detail = {
                    'index': index,
                    'source_file': file_path,
                    'subject_id': subject_id,
                    'session': self.session,
                    'task': task,
                    'copy_status': result.get('copy_status', 'unknown'),
                    'process_status': result.get('process_status', 'unknown'),
                    'bids_source_file': result.get('bids_file', None),
                    'bids_processed_file': result.get('processed_file_path', None),
                    'recording_duration': result.get('recording_duration', 0.0),
                    'recording_hours': result.get('recording_hours', 0.0),
                    'pipeline': pipeline_name,
                    'description': description,
                    'error': result.get('error', None)
                }
                results["details"].append(detail)
                    
                # 实时打印进度
                filename = Path(file_path).name
                if result.get('error'):
                    print(f"[{completed_count}/{len(file_paths)}] ❌ 处理失败: {filename}")
                    print(f"   错误: {result['error'][:100]}...")  # 截断长错误信息
                else:
                    print(f"[{completed_count}/{len(file_paths)}] ✅ 完成: {filename}")
                    print(f"   保存为: sub-{subject_id}_{self.session}")
                    print(f"   记录时长: {result.get('recording_duration', 0.0):.1f}秒 ({result.get('recording_hours', 0.0):.2f}小时)")
                    
            # except KeyboardInterrupt:
            #     print("\n用户中断处理，正在终止工作进程...")
            #     pool.terminate()
            #     pool.join()
            #     print("处理已中止")
            #     return results
            # except Exception as e:
            #     print(f"\n处理过程中发生错误: {e}")
            #     pool.terminate()
            #     pool.join()
            #     raise
        
        # 记录结束时间
        results["end_subject_id"] = self._format_subject_id(self.subject_counter - 1)
        results["processing_end_time"] = datetime.now().isoformat()
        
        # 按原始索引排序详情列表（如果需要保持顺序）
        results["details"].sort(key=lambda x: x['index'])
        
        # 创建处理报告
        self._create_processing_report(results, task, pipeline_name, description)
        
        print("\n" + "=" * 60)
        print(f"批量处理完成 (多进程)")
        print(f"总文件数: {results['total_files']}")
        print(f"成功复制源文件: {results['copy_success']}")
        print(f"成功保存处理数据: {results['processed_success']}")
        print(f"失败文件数: {results['processed_failed']}")
        print(f"本次处理总记录时长: {results['total_recording_hours']:.2f} 小时")
        print(f"subject_id范围: {results['start_subject_id']} - {results['end_subject_id']}")
        print(f"使用进程数: {num_processes}")
        print(f"BIDS目录: {self.bids_root}")
        
        # 打印当前数据集的累计记录时长
        print(f"当前数据集 '{self.dataset_name}' 累计记录时长: {self.total_recording_hours:.2f} 小时")
        
        return results


    def _process_single_file_worker(self, task_data: Tuple[int, Tuple[str, str]], 
                                task: str = "sleep",
                                process_func: Callable = None,
                                pipeline_name: str = "preprocessed",
                                description: str = "clean",
                                **kwargs) -> Dict[str, Any]:
        """
        单文件处理工作函数（用于多进程）
        
        Args:
            task_data: (索引, (文件路径, subject_id)) 元组
            task: 任务名称
            process_func: 处理函数
            pipeline_name: 流水线名称
            description: 数据描述
            **kwargs: 其他参数
            
        Returns:
            处理结果字典
        """
        index, (file_path, subject_id) = task_data
        
        result = {
            'index': index,
            'file_path': file_path,
            'subject_id': subject_id,
            'process_status': 'unknown',
            'copy_status': 'unknown',
            'recording_duration': 0.0,
            'recording_hours': 0.0,
            'bids_file': None,
            'processed_file_path': None,
            'error': None
        }
        
        # 1. 调用处理函数
        process_result = self.save_processed_to_derivatives(
            process_func,
            file_path,
            subject_id=subject_id,
            description=description,
            pipeline_name=pipeline_name,
            overwrite=False
        )
        
        result['process_status'] = process_result.get('status', 'unknown')
        result['processed_file_path'] = process_result.get('file_path', None)
        
        # 如果处理失败，记录错误
        if process_result.get('status') not in ['success', 'skipped']:
            result['error'] = process_result.get('message', '处理失败')

        
        # 2. 复制源文件到BIDS
        copy_result = self.copy_source_to_bids(
            source_file=file_path,
            subject_id=subject_id,
            overwrite=False
        )
        
        result['copy_status'] = copy_result.get('status', 'unknown')
        result['bids_file'] = copy_result.get('bids_file', None)
        
        # 记录时长信息
        if copy_result.get('status') == 'success':
            recording_seconds = copy_result.get('recording_duration', 0.0)
            recording_hours = copy_result.get('recording_hours', recording_seconds / 3600.0)
            result['recording_duration'] = recording_seconds
            result['recording_hours'] = recording_hours
                
        
        return result


    def _create_processing_report(self, results: Dict[str, Any], 
                                task: str, pipeline_name: str, description: str):
        """创建处理报告"""
        # 创建报告目录
        report_dir = self.bids_root / "derivatives" / "reports"
        report_dir.mkdir(parents=True, exist_ok=True)
        
        # 报告文件名包含时间戳
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        report_path = report_dir / f"processing_report_{self.dataset_name}_{timestamp}.txt"
        
        # 获取当前数据集的累计记录时长
        current_dataset_hours = self.total_recording_hours
        
        report = f"""# BIDS批量处理报告

                ## 基本信息
                - 数据集: {self.dataset_name}
                - 任务: {task}
                - Session: {self.session}
                - 处理流水线: {pipeline_name}
                - 数据描述: {description}
                - 处理开始时间: {results['processing_start_time']}
                - 处理结束时间: {results['processing_end_time']}

                ## 统计信息
                - 总文件数: {results['total_files']}
                - 成功复制源文件: {results['copy_success']}
                - 成功保存处理数据: {results['processed_success']}
                - 失败文件数: {results['processed_failed']}
                - 本次处理总记录时长: {results['total_recording_hours']:.2f} 小时
                - 当前数据集累计记录时长: {current_dataset_hours:.2f} 小时
                - 起始subject_id: {results['start_subject_id']}
                - 结束subject_id: {results['end_subject_id']}
                - 成功率: {results['processed_success'] / results['total_files'] * 100:.1f}% (如果总文件数>0)

                    ## 文件详情
                    """
        
        for detail in results["details"]:
            report += f"\n{detail['index']}. Subject: {detail.get('subject_id', 'unknown')}"
            report += f"\n   源文件: {Path(detail.get('source_file', '')).name}"
            report += f"\n   记录时长: {detail.get('recording_duration', 0.0):.1f} 秒 ({detail.get('recording_hours', 0.0):.2f} 小时)"
            report += f"\n   复制状态: {detail.get('copy_status', 'unknown')}"
            report += f"\n   处理状态: {detail.get('process_status', 'unknown')}"
            
            if detail.get('bids_source_file'):
                report += f"\n   BIDS源文件: {Path(detail.get('bids_source_file', '')).name}"
            
            if detail.get('bids_processed_file'):
                report += f"\n   BIDS处理文件: {Path(detail.get('bids_processed_file', '')).name}"
            
            if detail.get('error'):
                report += f"\n   错误: {detail.get('error')}"
            
            report += "\n"
        
        # 添加汇总信息
        report += f"\n## 汇总信息\n"
        report += f"处理完成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        report += f"本次处理总记录时长: {results['total_recording_hours']:.2f} 小时 ({results['total_recording_seconds']:.0f} 秒)\n"
        report += f"当前数据集累计记录时长: {current_dataset_hours:.2f} 小时\n"
        report += f"BIDS目录结构: {self.bids_root}\n"
        report += f"Derivatives目录: {self.bids_root / 'derivatives' / pipeline_name}\n"
        
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(report)
        
        print(f"详细报告已保存到: {report_path}")
        
        return report_path
    
    def get_dataset_info(self) -> List[Dict]:
        """获取所有数据集信息"""
        desc_path = self.bids_root / "dataset_description00.json"
        
        if desc_path.exists():
            with open(desc_path, 'r', encoding='utf-8') as f:
                dataset_desc = json.load(f)
            return dataset_desc.get("DatasetInfo", [])
        else:
            return []
    
    def print_summary(self):
        """打印数据集汇总信息"""
        print(f"\n{'='*60}")
        print(f"数据集汇总信息")
        print(f"{'='*60}")
        print(f"BIDS目录: {self.bids_root}")
        print(f"当前数据集: {self.dataset_name}")
        print(f"起始subject_id: {self._format_subject_id(self.start_subject_id)}")
        print(f"下一个subject_id: {self._format_subject_id(self.subject_counter)}")
        print(f"当前数据集累计记录时长: {self.total_recording_hours:.2f} 小时")
        
        # 读取dataset_description.json获取最新信息
        desc_path = self.bids_root / "dataset_description00.json"
        if desc_path.exists():
            with open(desc_path, 'r', encoding='utf-8') as f:
                dataset_desc = json.load(f)
            
            print(f"\n全局统计:")
            print(f"  总被试数: {dataset_desc.get('TotalSubjects', 0)}")
            print(f"  总记录时长: {dataset_desc.get('TotalRecordingHours', 0.0):.2f} 小时")
        
        dataset_info = self.get_dataset_info()
        if dataset_info:
            print(f"\n已处理的数据集 ({len(dataset_info)} 个):")
            for i, info in enumerate(dataset_info, 1):
                dataset_name = info.get('name', 'Unknown')
                is_current = "(当前)" if dataset_name == self.dataset_name else ""
                
                print(f"  {i}. {dataset_name} {is_current}")
                print(f"     文件数: {info.get('file_count', 0)}")
                print(f"     累计记录时长: {info.get('total_recording_hours', 0.0):.2f} 小时")
                print(f"     计划subject_id范围: {info.get('planned_start_subject_id', 'N/A')} - {info.get('planned_end_subject_id', 'N/A')}")
                print(f"     任务: {info.get('task', 'N/A')}")
                print(f"     session: {info.get('session', 'N/A')}")
                print(f"     创建时间: {info.get('creation_time', 'N/A')}")
        else:
            print(f"\n暂无数据集信息")

